### ISSUE TITLE
Is it static

### ISSUE THREAD

**Issue by ipchelnikov** [ilya-isupov/cleverVillageHouse#2]
Should not those fields be static? Otherwise I cannot get the idea:
```C++
ControlPanel controlPanel = ControlPanel();
PelletBurnerStateHolder pelletBurnerStateHolder = PelletBurnerStateHolder();
```
Even they are going to be static, it is better to replace the initialization from the class declaration

Plus to this, it does not have any sense to redefine the default constructor in case it is empty. However if it is just temporary and going to be filed out later, I am Ok with it.

Thanks =)

**Comment by ilya-isupov** [comment]
These are just to test and memorize part of implementation.
This will be re-implemented soon.

**Comment by ipchelnikov** [comment]
Ok  :ok_hand:
